#!/bin/bash -e

if [ ! -f "$HOME/.config/MangoHud/MangoHud.conf" ]; then
  # Create the directory if it doesn's exist
  mkdir -p "$HOME/.config/MangoHud"
  cat > $HOME/.config/MangoHud/MangoHud.conf <<EOL
# Config Generated by MangoJuice #
legacy_layout=false
gpu_stats
gpu_load_change
vram
gpu_core_clock
gpu_mem_clock
gpu_power
cpu_stats
cpu_load_change
core_load
core_load_change
cpu_mhz
fps
fps_metrics=avg,0.01,0.001
no_display
gpu_name
frame_timing
frame_timing_detailed
histogram
toggle_logging=Shift_L+F2
toggle_hud_position=Shift_R+F11
fps_limit_method=позже
toggle_fps_limit=Shift_L+F1
vsync=3
gl_vsync=1
none #filters
af=16
round_corners=9
background_alpha=0.5
position=top-right
toggle_hud=Shift_R+F12
gpu_color=2e9762
cpu_color=2e97cb
fps_value=30,60
fps_color=cc0000,ffaa7f,92e79a
gpu_load_value=60,90
gpu_load_color=92e79a,ffaa7f,cc0000
cpu_load_value=60,90
cpu_load_color=92e79a,ffaa7f,cc0000
background_color=000000
frametime_color=00ff00
vram_color=ad64c1
ram_color=c26693
wine_color=eb5b5b
engine_color=eb5b5b
text_color=ffffff
media_player_color=ffffff
network_color=e07b85
battery_color=92e79a
media_player_format={title};{artist};{album}
EOL
  chown "$UNAME:$UNAME" "$HOME/.config/MangoHud/MangoHud.conf"
  chmod 600 "$HOME/.config/MangoHud/MangoHud.conf"  #optional - read/write only by user
  echo ">> MangoHud.conf created at $HOME/.config/MangoHud/ and owned by $UNAME:$UNAME"
fi





cat > /usr/local/share/vulkan/implicit_layer.d/VkLayer_LS_frame_generation.json <<EOL


{


  "file_format_version": "1.0.0",


  "layer": {


    "name": "VK_LAYER_LS_frame_generation",


    "type": "GLOBAL",


    "api_version": "1.4.313",


    "library_path": "/usr/local/lib/liblsfg-vk.so",


    "implementation_version": "1",


    "description": "Lossless Scaling frame generation layer",


    "functions": {


      "vkGetInstanceProcAddr": "layer_vkGetInstanceProcAddr",


      "vkGetDeviceProcAddr": "layer_vkGetDeviceProcAddr"


    },


    "disable_environment": {


      "DISABLE_LSFG": "1"


    }


  }


}


EOL